spring:
  application:
    name: pag-control-back

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    root: INFO
    com.pedrohenrique.pagcontrolback: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"
  file:
    name: logs/pag-control-back.log

management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /
  endpoint:
    health:
      show-details: always

api:
    security:
      token:
        secret: ${JWT_SECRET}
