spring:
  application:
    name: pag-control-back

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    root: INFO
    com.pedrohenrique.pagcontrolback: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /
  endpoint:
    health:
      show-details: always

api:
    security:
      token:
        secret: ${JWT_SECRET}